spring.application.name=StayOnTest

# Derby en memoria SOLO para tests (no toca tu BD "database")
spring.datasource.url=jdbc:derby:memory:stayontestdb;create=true
spring.datasource.username=derbyuser
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
